chore(linux-installer): update app image file info
IgniteUI/app-builder-docfx pull request #26
Opened 2022-01-05 13:59 UTC by Svetloslav15

Close #25

2022-01-06 16:24 UTC, Aleksandyr requested changes

2022-01-06 16:24 UTC, Aleksandyr commented on en/running-desktop-app.md
> +Stay connected to your apps on any device Everyone needs instant access to their work no matter where they are – we’ve got you covered! Mobile, desktop, or web, App Builder is designed, so you can em
Stay connected to your apps on any device. Everyone needs
Are you missing a dot before Everyone?

2022-01-07 08:21 UTC, Aleksandyr approved these changes

2022-01-12 07:17 UTC, merged

2022-01-12 12:49 UTC, zdrawku commented
@hanastasov @Svetloslav15 could we keep a reference to the new "installers" page as part of the getting started as well. I want to ensure that whenever someone land on the Getting started page, he can stumble upon the installers explanation, without having the need to check the TOC in order to see that there is a separate doc for that