docs: use question icon instead of check for partially generated components
IgniteUI/app-builder-docfx pull request #44
Opened 2022-03-02 14:12 UTC by Lipata

2022-03-07 07:37 UTC, wnvko submitted a review, later dismissed

2022-03-08 07:04 UTC, wnvko submitted a review, later dismissed

2022-03-08 11:45 UTC, zdrawku approved these changes

2022-03-08 11:48 UTC, zdrawku requested changes
@Lipata could you please rebase to vNext

2022-03-08 11:57 UTC, closed without merging